### ISSUE TITLE
inode metrics

### ISSUE THREAD

**Issue by knweiss** [HewlettPackard/lustre_exporter#72]
These two metrics could be improved:

```
# HELP lustre_file_capacity The maximum number of inodes (objects) the filesystem can hold
# TYPE lustre_file_capacity gauge
lustre_file_capacity{ost="lustre-OST0000"} 3.047808e+07
# HELP lustre_files_free_now The number of inodes (objects) available
# TYPE lustre_files_free_now gauge
lustre_files_free_now{ost="lustre-OST0000"} 3.0477046e+07
```

- Inconsistency: "file" vs "files".
- Why "files" and not "inodes" anyway?
- IMHO the "_now" should be removed as it is completely redundant. (It appears
in some other metrics, too.)

Sorry for not catching this earlier.

**Comment by joehandzik** [comment]
We could definitely change from "file" to "inode", We were trying to minimize how much we changed the renaming of the metrics, but I agree that using "inode" makes the name more clear.

I could go either way on the other two problems. "lustre_inode_free_now" sounds a little weird to me, but that's because I'm trying to read it as a pseudo-sentence in my mind rather than reading the "inode" portion as an identifier.

We used the "_now" to maintain some consistency with the node_exporter (there's a metric that they have that uses "_now" as well).

@roclark, thoughts?
